In [11]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [12]:
tf.__version__

'2.12.0'

In [13]:
dataset = pd.read_csv('ANN_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,4] = le.fit_transform(X[:, 2])

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = .2, random_state = 1)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
print(X_train)

[[-0.99850112  1.71490137 -0.57273139 ... -1.55337352  0.97725852
   0.42739449]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352 -1.02327069
  -1.02548708]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.94479772]
 ...
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.14096853]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
   0.01781218]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017 -1.02327069
  -1.15822478]]


In [19]:
print(X_test)

[[ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.05360571]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017 -1.02327069
  -0.58392685]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352  0.97725852
  -0.16685331]
 ...
 [-0.99850112 -0.58312392  1.74601919 ... -1.55337352  0.97725852
   1.0669965 ]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
   1.13101314]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.88790165]]


In [20]:
#initalizing the ANN

In [21]:
ann = tf.keras.models.Sequential()

In [22]:
# adding the hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [24]:
# adding another hidden layer, every time you copypaste code
# you create another hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [26]:
#output layer

In [27]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [28]:
#Training the ANN

In [29]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [30]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6974 - accuracy: 0.5755
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5020 - accuracy: 0.7956
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4562 - accuracy: 0.7996
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4441 - accuracy: 0.8045
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4371 - accuracy: 0.8079
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4308 - accuracy: 0.8134
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4231 - accuracy: 0.8129
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4134 - accuracy: 0.8192
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4015 - accuracy: 0.8284
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3883 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3416 - accuracy: 0.8619
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3415 - accuracy: 0.8602
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3411 - accuracy: 0.8609
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3413 - accuracy: 0.8606
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3408 - accuracy: 0.8591
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3405 - accuracy: 0.8605
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3405 - accuracy: 0.8616
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3405 - accuracy: 0.8602
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3400 - accuracy: 0.8615
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3400 - accuracy: 

In [31]:
# epoch = number of times it backpropogates

In [32]:
y_pred = ann.predict(X_test)
y_pred = (y_pred >0.5)

63/63 [==============================] - 0s 3ms/step


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)

[[1535   50]
 [ 215  200]]


In [35]:
accuracy_score(Y_test,y_pred)

0.8675